name: ppi-toolkit
channels:
  - nvidia
  - pytorch
  - dglteam/label/th24_cu121
  - bioconda
  - defaults
  - conda-forge
  - milagraph
  - pyg
dependencies:
  - python=3.10
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - scipy=1.13.1
  - scikit-learn=1.5.2
  - pandas=2.2.3
  - dgl
  - hmmer=3.4
  - hhsuite=3.3.0
  - kalign2
  - mmseqs2=15.6f452
  - rdkit=2024.03.6
  - modelcif=1.1
  - openmm=8.1.2
  - pdbfixer
  - py3dmol=2.3.0
  - tqdm
  - foldseek
  - accelerate
  - huggingface_hub
  - safetensors
  - lightning
  - torchmetrics
  - dacite
  - ply
  - torchdrug
  - pymol-open-source
  - python-lmdb
  - pyg=*=*cu*
  - pip
  - pip:
      - deepspeed
      - hydra-core
      - networkx
      - packaging
      - ninja
      - termcolor
      - DSSPparser
      - biopython==1.84
      - requests==2.32.3
      - setuptools==75.1.0
      - pybel==0.15.5
      - dm-tree
      - mkdocs
      - easydict
      - e3nn
      - pynvml
      - wandb
      - git+https://github.com/NVIDIA/dllogger.git
      - git+https://github.com/google-deepmind/alphafold.git

