name: update sphinx
on: workflow_dispatch
jobs:
  documentation:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - uses: conda-incubator/setup-miniconda@v3
          with:
            auto-activate-base: true
            activate-environment: "deepfold2-dev"
            environment-file: backbone/DeepFoldPublic/dev.yml
            channels: pytorch, nvidia, bioconda, conda-forge, defaults
            channel-priority: flexible
            allow-softlinks: true
            show-channel-urls: true
        - shell: bash -el {0}
          run: |
            conda activate deepfold2-dev
            cd backbone/DeepFoldPublic
            pip install .
            conda install sphinx
            pip install furo
            cd ../../docs
            make html
        - uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: build/html
          
