name: update sphinx
on: workflow_dispatch
jobs:
  clone:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - uses: actions/cache@v3
          env:
            CACHE_NUMBER: 0
          with:
            path: ~/conda_pkgs_dir
            key:
              ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
              hashFiles('backbone/DeepFoldPublic/dev.yml') }}
        - uses: conda-incubator/setup-miniconda@v3
          with:
            activate-environment: anaconda-client-env
            environment-file: backbone/DeepFoldPublic/dev.yml
            auto-activate-base: true
            channel-priority: flexible
            allow-softlinks: true
            show-channel-urls: true
            use-only-tar-bz2: true
        - run: conda activate deepfold2-dev
        - run: pip install .
        - run: conda install sphinx
        - run: pip install furo
        - run: cd docs
        - run: make html