name: update sphinx
on: workflow_dispatch
jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: "ppi-toolkit-doc"
          environment-file: docs/environment_doc.yml
          channels: pytorch, nvidia, bioconda, conda-forge, defaults
          channel-priority: flexible
          allow-softlinks: true
          show-channel-urls: true
      - shell: bash -el {0}
        run: |
          conda activate ppi-toolkit-doc
          git clone https://github.com/NVIDIA/apex
          cd apex
          pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./
          cd ../
          conda install -y sphinx
          pip install furo
          pip install git+https://github.com/google-deepmind/alphafold.git
          sphinx-apidoc -d 8 -F -o docs/source/backbone/deepfold backbone/DeepFoldPublic/deepfold
          sphinx-apidoc -d 8 -F -o docs/source/backbone/se3_transformer backbone/RoseTTAFold2/SE3Transformer/se3_transformer
          sphinx-apidoc -d 8 -F -o docs/source/backbone/network backbone/RoseTTAFold2/network
          sphinx-apidoc -d 8 -F -o docs/source/tool/bis_protein_structure tool/BIS-ProteinStructure-libraries
          sphinx-apidoc -d 8 -F -o docs/source/tool/gd_dl tool/galaxydock_dl/src/gd_dl
          cd docs
          make html
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/build/html
          
