name: update sphinx
on: workflow_dispatch
jobs:
  clone:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - uses: conda-incubator/setup-miniconda@v3
          with:
            environment-file: backbone/DeepFoldPublic/dev.yml
        - run: conda activate deepfold2-dev
        - run: pip install .
        - run: conda install sphinx
        - run: cd docs
        - run: make html